### ISSUE TITLE
Error while running in Python3

### ISSUE THREAD

**Issue by JeromeGNJ** [csev/py4inf#10]
Hi Sir,

I am learning Python from your Python for Informatics book.

while going via '13.8 Security and API usage' in page 162.

I am trying to practice the programs in that page, i found
At Line 575, in Oauth.py, 'Undefined variable sha'.
And many errors while running twitter1.py, because it accesses oauth.py, hidden.py, and twurl.py

As i am working with Python3 (both windows and Ubuntu), not Python2 which the book was intended to. So please guide me in Python3.

Thankyou !

**Comment by csev** [comment]
The python 3 version of the book and code is at www.py4e.com
